// <auto-generated />
using System;
using Mercury.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mercury.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260831113723_UpdateSeedAccounts")]
    partial class UpdateSeedAccounts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mercury.Ledger.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_code");

                    b.ToTable("accounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "STORE-A-PENDING",
                            Name = "Store A – Pending Settlement",
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "STORE-A-CASH-TILL",
                            Name = "Store A – Cash Till",
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Code = "PHARMACY-BANK",
                            Name = "Pharmacy Bank Account",
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Code = "SALES-REVENUE-A",
                            Name = "Sales Revenue – Store A",
                            Type = "Revenue"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Code = "REFUNDS-A",
                            Name = "Refunds – Store A",
                            Type = "Expense"
                        });
                });

            modelBuilder.Entity("Mercury.Ledger.Entities.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("channel");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("reference");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_journal_entries");

                    b.HasIndex("Reference")
                        .HasDatabaseName("ix_journal_entries_reference");

                    b.ToTable("journal_entries", (string)null);
                });

            modelBuilder.Entity("Mercury.Ledger.Entities.JournalLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("direction");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.HasKey("Id")
                        .HasName("pk_journal_lines");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_journal_lines_account_id");

                    b.HasIndex("JournalEntryId")
                        .HasDatabaseName("ix_journal_lines_journal_entry_id");

                    b.ToTable("journal_lines", (string)null);
                });

            modelBuilder.Entity("Mercury.Ledger.Entities.JournalLine", b =>
                {
                    b.HasOne("Mercury.Ledger.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_journal_lines_accounts_account_id");

                    b.HasOne("Mercury.Ledger.Entities.JournalEntry", null)
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_journal_lines_journal_entries_journal_entry_id");
                });

            modelBuilder.Entity("Mercury.Ledger.Entities.JournalEntry", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
